### ISSUE TITLE
Previous records on the site 

### ISSUE THREAD

**Issue by Anikaaasingh** [IIT-BHU-SPORTS-FEST/Spardha-22#36]
I would suggest to have previous records or maybe the highest records to be put on the site for reference.

**Comment by omprakash1999mina** [comment]
Thanks for reviewing
Please elaborate more , which type of records you want on the site .

**Comment by Anikaaasingh** [comment]
There are some sports like athletics or weightlifting  etc in which the previous best timings(best ever records for eg x sec in 100 m men) or weights can be made available  on the site.

**Comment by omprakash1999mina** [comment]
Ok, Nice point
we would like to implement this thing .
And you're most welcome if you want to implement this section.

**Comment by Anikaaasingh** [comment]
Yes I would love to work  on this section but I would require guidance and path how to proceed  for it as I am a beginner only right  now.

**Comment by omprakash1999mina** [comment]
You can work as a team member and If want to work in tech team spardha'22 contact on 8955616391(whatsapp only)

**Comment by omprakash1999mina** [comment]
> You can work as a team member and If want to work in tech team spardha'22 contact on 8955616391(whatsapp only)

Tech Team Head contact

**Comment by Anikaaasingh** [comment]
Sure thanks
